---
title: "Resume"
format: html
---

**Sara M. McLaughlin** 

Fort Collins, CO \| saramclaughlin0\@gmail.com \| (815) 514-0878  

**BIOLOGICAL CONSERVATION\| SUSTAINABILITY RESEARCH\| ECOLOGICAL RESTORATION** 

An emerging conservation biologist with a special interest in ecological fieldwork, I am skilled in scientific research, data organization and analysis, and sustainable practices. I seek to utilize my expertise in organizations dedicated to conservation ecology and biology and apply my core competencies which include:    

-   Experience with GPS and GIS systems (ArcGIS Pro and Online) 

<!-- -->

-   Thoroughness and strong attention to detail 

<!-- -->

-   Self-sufficiency and ability to work independently  

<!-- -->

-   Excellent time management and organizational skills 

<!-- -->

-   Proficiency in hiking, camping, and off-road navigation in challenging conditions 

 

**EDUCATION** 

**Colorado State University, Fort Collins, CO** 								May 2026 

Bachelor of Science, **Ecosystem Science and Sustainability** 	

Bachelor of Science, **Biology** 

**GPA: 3.98** 

                      			 

**ECOLOGICAL AND SUSTAINABILITY EXPERIENCE** 

**Student Ambassador - CSU Energy Institute** 						              October 2023 – Present 

Fort Collins, CO						 

-   Develop a core understanding of over twenty sustainability research laboratories 

<!-- -->

-   Organize and analyze facility research data using Microsoft Excel and other Office applications 

<!-- -->

-   Deliver educational outreach demonstrations on climate change and sustainable practices  

<!-- -->

-   Conduct guided tours for diverse audiences 

**Horticulture Intern - The Gardens on Spring Creek**					        May 2024 – August 2024 

Fort Collins, CO 

-   Assisted various horticulturists with plant management and identification techniques 

<!-- -->

-   Managed, collected, and analyzed extensive plant and soil data 

<!-- -->

-   Collaborated and communicated with a large team and volunteer groups effectively 

<!-- -->

-   Executed plant upkeep in outdoor and greenhouse environments 

<!-- -->

-   Worked outdoors in adverse conditions with extreme physical activity 

**Field Worker - Bronkberry Farms** 							           April 2020 – August 2022 

Shorewood, IL  

-   Oversaw planting, care, and harvesting of produce and other vegetation in the field 

<!-- -->

-   Identified and treated plant diseases and infections   

<!-- -->

-   Performed intensive manual labor in challenging outdoor environments 

 

**RESTORATION VOLUNTEER EXPERIENCE** 

**Field Volunteer - Wildlands Restoration Volunteers** 						     May 2024 – Present 

Colorado 

-   Contributed to ecological restoration projects in remote locations 

<!-- -->

-   Carried out physically demanding tasks in adverse outdoor conditions 

 

**AWARDS & CERTIFICATIONS**		 

**Green and Gold Scholarship Recipient**, Colorado State University 				

Fall 2022 – Spring 2026 

**Dean's List Certification**, Colorado State University

Fall 2022 – Present 
